.TH IKAROS 1 "2023-04-13" "ikaros" "User Manual"
.SH NAME
.RS 4
ikaros - Az Ikaros kezeli az eszközök illesztőprogramjait
.RE
.SH SYNOPSIS
.RS 4
ikaros [command] [flags] [arguments]
.RE
.SH DESCRIPTION
.RS 4
Az Ikaros egy parancssoros eszköz az eszközök illesztőprogramjainak kezeléséhez
.RE
.SH OPTIONS
.SH IKAROS COMMANDS
.RS 4
\fBlist-devices\fP
.RS 4
Eszközök listája
.PP
.RE
\fBinstall\fP
.RS 4
Telepítsen egy illesztőprogramot
.PP
.RE
\fBauto-install\fP
.RS 4
Automatikusan telepíti a megfelelő illesztőprogramokat
.PP
.RE
.RE
.SH AUTHORS
.PP
Written by Vanilla OS contributors\&.
.SH REPORT BUGS TO
.PP
https://github\&.com/vanilla-os/ikaros/issues
.SH LICENSE
.PP
GPLv3+: GNU GPL version 3 or later <http://gnu\&.org/licenses/gpl\&.html>\&.
.SH IKAROS SUBCOMMANDS
.SH SUBCOMMAND LIST-DEVICES
.RS 4
Eszközök listája
.RE
.SS SYNOPSIS
.RS 4
\fBlist-devices\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Az összes eszköz listázása
.RE
.SS OPTIONS
  -j, --json   Kimenet JSON-ként
.PP
.SS GLOBAL OPTIONS
.SS EXAMPLES
.RS 4
ikaros list-devices
.RE
.SH SUBCOMMAND INSTALL
.RS 4
Telepítsen egy illesztőprogramot
.RE
.SS SYNOPSIS
.RS 4
\fBinstall\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Telepítsen egy illesztőprogramot
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
.SS EXAMPLES
.RS 4
ikaros install
.RE
.SH SUBCOMMAND AUTO-INSTALL
.RS 4
Automatikusan telepíti a megfelelő illesztőprogramokat
.RE
.SS SYNOPSIS
.RS 4
\fBauto-install\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Automatikusan telepíti a megfelelő illesztőprogramokat minden eszközhöz
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
.SS EXAMPLES
.RS 4
ikaros auto-install
.RE

