.TH IKAROS 1 "2023-03-22" "ikaros" "User Manual"
.SH NAME
.RS 4
ikaros - Ikaros beheert de drivers voor uw apparaten
.RE
.SH SYNOPSIS
.RS 4
ikaros [command] [flags] [arguments]
.RE
.SH DESCRIPTION
.RS 4
Ikaros is een opdrachtregelprogramma voor het beheer van stuurprogramma's voor uw apparaten
.RE
.SH OPTIONS
.SH IKAROS COMMANDS
.RS 4
\fBlist-devices\fP
.RS 4
Apparatenlijst
.PP
.RE
\fBinstall\fP
.RS 4
Stuurprogramma installeren
.PP
.RE
\fBauto-install\fP
.RS 4
Automatisch juiste stuurprogramma's installeren
.PP
.RE
.RE
.SH AUTHORS
.PP
Written by Vanilla OS contributors\&.
.SH REPORT BUGS TO
.PP
https://github\&.com/vanilla-os/ikaros/issues
.SH LICENSE
.PP
GPLv3+: GNU GPL version 3 or later <http://gnu\&.org/licenses/gpl\&.html>\&.
.SH IKAROS SUBCOMMANDS
.SH SUBCOMMAND LIST-DEVICES
.RS 4
Apparatenlijst
.RE
.SS SYNOPSIS
.RS 4
\fBlist-devices\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Lijst van alle apparaten tonen
.RE
.SS OPTIONS
  -j, --json   JSON-uitvoer
.PP
.SS GLOBAL OPTIONS
.SS EXAMPLES
.RS 4
ikaros list-devices
.RE
.SH SUBCOMMAND INSTALL
.RS 4
Stuurprogramma installeren
.RE
.SS SYNOPSIS
.RS 4
\fBinstall\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Stuurprogramma installeren
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
.SS EXAMPLES
.RS 4
ikaros install
.RE
.SH SUBCOMMAND AUTO-INSTALL
.RS 4
Automatisch juiste stuurprogramma's installeren
.RE
.SS SYNOPSIS
.RS 4
\fBauto-install\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Automatisch de juiste stuurprogramma's voor alle apparaten installeren
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
.SS EXAMPLES
.RS 4
ikaros auto-install
.RE

