.TH IKAROS 1 "2023-04-13" "ikaros" "User Manual"
.SH NAME
.RS 4
ikaros - Ikaros administras zorgilojn por viaj aparatoj
.RE
.SH SYNOPSIS
.RS 4
ikaros [command] [flags] [arguments]
.RE
.SH DESCRIPTION
.RS 4
Ikaros is a command line tool for managing drivers for your devices
.RE
.SH OPTIONS
.SH IKAROS COMMANDS
.RS 4
\fBlist-devices\fP
.RS 4
Listigi aparatojn
.PP
.RE
\fBinstall\fP
.RS 4
Instali zorgilon
.PP
.RE
\fBauto-install\fP
.RS 4
Aŭtomate instali taŭgajn zorgilojn
.PP
.RE
.RE
.SH AUTHORS
.PP
Written by Vanilla OS contributors\&.
.SH REPORT BUGS TO
.PP
https://github\&.com/vanilla-os/ikaros/issues
.SH LICENSE
.PP
GPLv3+: GNU GPL version 3 or later <http://gnu\&.org/licenses/gpl\&.html>\&.
.SH IKAROS SUBCOMMANDS
.SH SUBCOMMAND LIST-DEVICES
.RS 4
Listigi aparatojn
.RE
.SS SYNOPSIS
.RS 4
\fBlist-devices\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Listigi ĉiujn aparatojn
.RE
.SS OPTIONS
  -j, --json   Eligi kiel JSON
.PP
.SS GLOBAL OPTIONS
.SS EXAMPLES
.RS 4
ikaros list-devices
.RE
.SH SUBCOMMAND INSTALL
.RS 4
Instali zorgilon
.RE
.SS SYNOPSIS
.RS 4
\fBinstall\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Instali zorgilon
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
.SS EXAMPLES
.RS 4
ikaros install
.RE
.SH SUBCOMMAND AUTO-INSTALL
.RS 4
Aŭtomate instali taŭgajn zorgilojn
.RE
.SS SYNOPSIS
.RS 4
\fBauto-install\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Aŭtomate instali taŭgajn zorgilojn por ĉiuj aparatoj
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
.SS EXAMPLES
.RS 4
ikaros auto-install
.RE

