.TH IKAROS 1 "2023-04-13" "ikaros" "User Manual"
.SH NAME
.RS 4
ikaros - Ikaros gestionează drivere pentru dispozitivele dvs
.RE
.SH SYNOPSIS
.RS 4
ikaros [command] [flags] [arguments]
.RE
.SH DESCRIPTION
.RS 4
Ikaros este un instrument de linie de comandă pentru gestionarea driverelor pentru dispozitivele dvs
.RE
.SH OPTIONS
.SH IKAROS COMMANDS
.RS 4
\fBlist-devices\fP
.RS 4
Listați dispozitivele
.PP
.RE
\fBinstall\fP
.RS 4
Instalați un driver
.PP
.RE
\fBauto-install\fP
.RS 4
Instalați automat driverele corecte
.PP
.RE
.RE
.SH AUTHORS
.PP
Written by Vanilla OS contributors\&.
.SH REPORT BUGS TO
.PP
https://github\&.com/vanilla-os/ikaros/issues
.SH LICENSE
.PP
GPLv3+: GNU GPL version 3 or later <http://gnu\&.org/licenses/gpl\&.html>\&.
.SH IKAROS SUBCOMMANDS
.SH SUBCOMMAND LIST-DEVICES
.RS 4
Listați dispozitivele
.RE
.SS SYNOPSIS
.RS 4
\fBlist-devices\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Listați toate dispozitivele
.RE
.SS OPTIONS
  -j, --json   Ieșire ca JSON
.PP
.SS GLOBAL OPTIONS
.SS EXAMPLES
.RS 4
ikaros list-devices
.RE
.SH SUBCOMMAND INSTALL
.RS 4
Instalați un driver
.RE
.SS SYNOPSIS
.RS 4
\fBinstall\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Instalați un driver
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
.SS EXAMPLES
.RS 4
ikaros install
.RE
.SH SUBCOMMAND AUTO-INSTALL
.RS 4
Instalați automat driverele corecte
.RE
.SS SYNOPSIS
.RS 4
\fBauto-install\fP [command] [flags] [arguments]
.RE
.SS DESCRIPTION
.RS 4
.TP 4
Instalați automat driverele corecte pentru toate dispozitivele
.RE
.SS OPTIONS
.SS GLOBAL OPTIONS
.SS EXAMPLES
.RS 4
ikaros auto-install
.RE

