name: Go

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: registry.vanillaos.org/vanillaos/pico:main

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Install build dependencies
      run: |
          apt-get update
          apt-get install -y pkg-config build-essential

    - name: Build
      run: go build -o ikaros
