name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Install build dependencies
      run: |
          apt-get update
          apt-get install -y pkg-config build-essential

    - name: Build
      run: go build -o ikaros

    - name: Compress
      run: tar -czvf ikaros.tar.gz ikaros

    - name: Compress-manpage
      run: tar -czvf ikaros-man.tar.gz man/ikaros.1

    - uses: softprops/action-gh-release@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "continuous"
        prerelease: true
        name: "Continuous Build"
        files: |
          ikaros.tar.gz
          ikaros-man.tar.gz
